// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace gocnn {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_message_2eproto();
void protobuf_AssignDesc_message_2eproto();
void protobuf_ShutdownFile_message_2eproto();

class RequestV1;
class RequestV2;
class ResponseV1;
class ResponseV2;

// ===================================================================

class RequestV1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gocnn.RequestV1) */ {
 public:
  RequestV1();
  virtual ~RequestV1();

  RequestV1(const RequestV1& from);

  inline RequestV1& operator=(const RequestV1& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestV1& default_instance();

  void Swap(RequestV1* other);

  // implements Message ----------------------------------------------

  inline RequestV1* New() const { return New(NULL); }

  RequestV1* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestV1& from);
  void MergeFrom(const RequestV1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RequestV1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 board_size = 1;
  void clear_board_size();
  static const int kBoardSizeFieldNumber = 1;
  ::google::protobuf::int32 board_size() const;
  void set_board_size(::google::protobuf::int32 value);

  // repeated bool our_group_lib1 = 2;
  int our_group_lib1_size() const;
  void clear_our_group_lib1();
  static const int kOurGroupLib1FieldNumber = 2;
  bool our_group_lib1(int index) const;
  void set_our_group_lib1(int index, bool value);
  void add_our_group_lib1(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      our_group_lib1() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_our_group_lib1();

  // repeated bool our_group_lib2 = 3;
  int our_group_lib2_size() const;
  void clear_our_group_lib2();
  static const int kOurGroupLib2FieldNumber = 3;
  bool our_group_lib2(int index) const;
  void set_our_group_lib2(int index, bool value);
  void add_our_group_lib2(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      our_group_lib2() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_our_group_lib2();

  // repeated bool our_group_lib3_plus = 4;
  int our_group_lib3_plus_size() const;
  void clear_our_group_lib3_plus();
  static const int kOurGroupLib3PlusFieldNumber = 4;
  bool our_group_lib3_plus(int index) const;
  void set_our_group_lib3_plus(int index, bool value);
  void add_our_group_lib3_plus(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      our_group_lib3_plus() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_our_group_lib3_plus();

  // repeated bool oppo_group_lib1 = 5;
  int oppo_group_lib1_size() const;
  void clear_oppo_group_lib1();
  static const int kOppoGroupLib1FieldNumber = 5;
  bool oppo_group_lib1(int index) const;
  void set_oppo_group_lib1(int index, bool value);
  void add_oppo_group_lib1(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      oppo_group_lib1() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_oppo_group_lib1();

  // repeated bool oppo_group_lib2 = 6;
  int oppo_group_lib2_size() const;
  void clear_oppo_group_lib2();
  static const int kOppoGroupLib2FieldNumber = 6;
  bool oppo_group_lib2(int index) const;
  void set_oppo_group_lib2(int index, bool value);
  void add_oppo_group_lib2(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      oppo_group_lib2() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_oppo_group_lib2();

  // repeated bool oppo_group_lib3_plus = 7;
  int oppo_group_lib3_plus_size() const;
  void clear_oppo_group_lib3_plus();
  static const int kOppoGroupLib3PlusFieldNumber = 7;
  bool oppo_group_lib3_plus(int index) const;
  void set_oppo_group_lib3_plus(int index, bool value);
  void add_oppo_group_lib3_plus(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      oppo_group_lib3_plus() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_oppo_group_lib3_plus();

  // repeated bool is_simple_ko = 8;
  int is_simple_ko_size() const;
  void clear_is_simple_ko();
  static const int kIsSimpleKoFieldNumber = 8;
  bool is_simple_ko(int index) const;
  void set_is_simple_ko(int index, bool value);
  void add_is_simple_ko(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      is_simple_ko() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_is_simple_ko();

  // @@protoc_insertion_point(class_scope:gocnn.RequestV1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedField< bool > our_group_lib1_;
  mutable int _our_group_lib1_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > our_group_lib2_;
  mutable int _our_group_lib2_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > our_group_lib3_plus_;
  mutable int _our_group_lib3_plus_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > oppo_group_lib1_;
  mutable int _oppo_group_lib1_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > oppo_group_lib2_;
  mutable int _oppo_group_lib2_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > oppo_group_lib3_plus_;
  mutable int _oppo_group_lib3_plus_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > is_simple_ko_;
  mutable int _is_simple_ko_cached_byte_size_;
  ::google::protobuf::int32 board_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static RequestV1* default_instance_;
};
// -------------------------------------------------------------------

class ResponseV1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gocnn.ResponseV1) */ {
 public:
  ResponseV1();
  virtual ~ResponseV1();

  ResponseV1(const ResponseV1& from);

  inline ResponseV1& operator=(const ResponseV1& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseV1& default_instance();

  void Swap(ResponseV1* other);

  // implements Message ----------------------------------------------

  inline ResponseV1* New() const { return New(NULL); }

  ResponseV1* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseV1& from);
  void MergeFrom(const ResponseV1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ResponseV1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 board_size = 1;
  void clear_board_size();
  static const int kBoardSizeFieldNumber = 1;
  ::google::protobuf::int32 board_size() const;
  void set_board_size(::google::protobuf::int32 value);

  // repeated float possibility = 2;
  int possibility_size() const;
  void clear_possibility();
  static const int kPossibilityFieldNumber = 2;
  float possibility(int index) const;
  void set_possibility(int index, float value);
  void add_possibility(float value);
  const ::google::protobuf::RepeatedField< float >&
      possibility() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_possibility();

  // @@protoc_insertion_point(class_scope:gocnn.ResponseV1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedField< float > possibility_;
  mutable int _possibility_cached_byte_size_;
  ::google::protobuf::int32 board_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static ResponseV1* default_instance_;
};
// -------------------------------------------------------------------

class RequestV2 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gocnn.RequestV2) */ {
 public:
  RequestV2();
  virtual ~RequestV2();

  RequestV2(const RequestV2& from);

  inline RequestV2& operator=(const RequestV2& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestV2& default_instance();

  void Swap(RequestV2* other);

  // implements Message ----------------------------------------------

  inline RequestV2* New() const { return New(NULL); }

  RequestV2* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestV2& from);
  void MergeFrom(const RequestV2& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RequestV2* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 board_size = 1;
  void clear_board_size();
  static const int kBoardSizeFieldNumber = 1;
  ::google::protobuf::int32 board_size() const;
  void set_board_size(::google::protobuf::int32 value);

  // repeated bool stone_color_our = 2;
  int stone_color_our_size() const;
  void clear_stone_color_our();
  static const int kStoneColorOurFieldNumber = 2;
  bool stone_color_our(int index) const;
  void set_stone_color_our(int index, bool value);
  void add_stone_color_our(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      stone_color_our() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_stone_color_our();

  // repeated bool stone_color_oppo = 3;
  int stone_color_oppo_size() const;
  void clear_stone_color_oppo();
  static const int kStoneColorOppoFieldNumber = 3;
  bool stone_color_oppo(int index) const;
  void set_stone_color_oppo(int index, bool value);
  void add_stone_color_oppo(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      stone_color_oppo() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_stone_color_oppo();

  // repeated bool stone_color_empty = 4;
  int stone_color_empty_size() const;
  void clear_stone_color_empty();
  static const int kStoneColorEmptyFieldNumber = 4;
  bool stone_color_empty(int index) const;
  void set_stone_color_empty(int index, bool value);
  void add_stone_color_empty(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      stone_color_empty() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_stone_color_empty();

  // repeated bool turns_since_one = 5;
  int turns_since_one_size() const;
  void clear_turns_since_one();
  static const int kTurnsSinceOneFieldNumber = 5;
  bool turns_since_one(int index) const;
  void set_turns_since_one(int index, bool value);
  void add_turns_since_one(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      turns_since_one() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_turns_since_one();

  // repeated bool turns_since_two = 6;
  int turns_since_two_size() const;
  void clear_turns_since_two();
  static const int kTurnsSinceTwoFieldNumber = 6;
  bool turns_since_two(int index) const;
  void set_turns_since_two(int index, bool value);
  void add_turns_since_two(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      turns_since_two() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_turns_since_two();

  // repeated bool turns_since_three = 7;
  int turns_since_three_size() const;
  void clear_turns_since_three();
  static const int kTurnsSinceThreeFieldNumber = 7;
  bool turns_since_three(int index) const;
  void set_turns_since_three(int index, bool value);
  void add_turns_since_three(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      turns_since_three() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_turns_since_three();

  // repeated bool turns_since_four = 8;
  int turns_since_four_size() const;
  void clear_turns_since_four();
  static const int kTurnsSinceFourFieldNumber = 8;
  bool turns_since_four(int index) const;
  void set_turns_since_four(int index, bool value);
  void add_turns_since_four(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      turns_since_four() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_turns_since_four();

  // repeated bool turns_since_five = 9;
  int turns_since_five_size() const;
  void clear_turns_since_five();
  static const int kTurnsSinceFiveFieldNumber = 9;
  bool turns_since_five(int index) const;
  void set_turns_since_five(int index, bool value);
  void add_turns_since_five(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      turns_since_five() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_turns_since_five();

  // repeated bool turns_since_six = 10;
  int turns_since_six_size() const;
  void clear_turns_since_six();
  static const int kTurnsSinceSixFieldNumber = 10;
  bool turns_since_six(int index) const;
  void set_turns_since_six(int index, bool value);
  void add_turns_since_six(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      turns_since_six() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_turns_since_six();

  // repeated bool turns_since_seven = 11;
  int turns_since_seven_size() const;
  void clear_turns_since_seven();
  static const int kTurnsSinceSevenFieldNumber = 11;
  bool turns_since_seven(int index) const;
  void set_turns_since_seven(int index, bool value);
  void add_turns_since_seven(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      turns_since_seven() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_turns_since_seven();

  // repeated bool turns_since_more = 12;
  int turns_since_more_size() const;
  void clear_turns_since_more();
  static const int kTurnsSinceMoreFieldNumber = 12;
  bool turns_since_more(int index) const;
  void set_turns_since_more(int index, bool value);
  void add_turns_since_more(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      turns_since_more() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_turns_since_more();

  // repeated bool liberties_our_one = 13;
  int liberties_our_one_size() const;
  void clear_liberties_our_one();
  static const int kLibertiesOurOneFieldNumber = 13;
  bool liberties_our_one(int index) const;
  void set_liberties_our_one(int index, bool value);
  void add_liberties_our_one(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      liberties_our_one() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_liberties_our_one();

  // repeated bool liberties_our_two = 14;
  int liberties_our_two_size() const;
  void clear_liberties_our_two();
  static const int kLibertiesOurTwoFieldNumber = 14;
  bool liberties_our_two(int index) const;
  void set_liberties_our_two(int index, bool value);
  void add_liberties_our_two(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      liberties_our_two() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_liberties_our_two();

  // repeated bool liberties_our_three = 15;
  int liberties_our_three_size() const;
  void clear_liberties_our_three();
  static const int kLibertiesOurThreeFieldNumber = 15;
  bool liberties_our_three(int index) const;
  void set_liberties_our_three(int index, bool value);
  void add_liberties_our_three(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      liberties_our_three() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_liberties_our_three();

  // repeated bool liberties_our_more = 16;
  int liberties_our_more_size() const;
  void clear_liberties_our_more();
  static const int kLibertiesOurMoreFieldNumber = 16;
  bool liberties_our_more(int index) const;
  void set_liberties_our_more(int index, bool value);
  void add_liberties_our_more(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      liberties_our_more() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_liberties_our_more();

  // repeated bool liberties_oppo_one = 17;
  int liberties_oppo_one_size() const;
  void clear_liberties_oppo_one();
  static const int kLibertiesOppoOneFieldNumber = 17;
  bool liberties_oppo_one(int index) const;
  void set_liberties_oppo_one(int index, bool value);
  void add_liberties_oppo_one(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      liberties_oppo_one() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_liberties_oppo_one();

  // repeated bool liberties_oppo_two = 18;
  int liberties_oppo_two_size() const;
  void clear_liberties_oppo_two();
  static const int kLibertiesOppoTwoFieldNumber = 18;
  bool liberties_oppo_two(int index) const;
  void set_liberties_oppo_two(int index, bool value);
  void add_liberties_oppo_two(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      liberties_oppo_two() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_liberties_oppo_two();

  // repeated bool liberties_oppo_three = 19;
  int liberties_oppo_three_size() const;
  void clear_liberties_oppo_three();
  static const int kLibertiesOppoThreeFieldNumber = 19;
  bool liberties_oppo_three(int index) const;
  void set_liberties_oppo_three(int index, bool value);
  void add_liberties_oppo_three(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      liberties_oppo_three() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_liberties_oppo_three();

  // repeated bool liberties_oppo_more = 20;
  int liberties_oppo_more_size() const;
  void clear_liberties_oppo_more();
  static const int kLibertiesOppoMoreFieldNumber = 20;
  bool liberties_oppo_more(int index) const;
  void set_liberties_oppo_more(int index, bool value);
  void add_liberties_oppo_more(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      liberties_oppo_more() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_liberties_oppo_more();

  // repeated bool capture_size_one = 21;
  int capture_size_one_size() const;
  void clear_capture_size_one();
  static const int kCaptureSizeOneFieldNumber = 21;
  bool capture_size_one(int index) const;
  void set_capture_size_one(int index, bool value);
  void add_capture_size_one(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      capture_size_one() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_capture_size_one();

  // repeated bool capture_size_two = 22;
  int capture_size_two_size() const;
  void clear_capture_size_two();
  static const int kCaptureSizeTwoFieldNumber = 22;
  bool capture_size_two(int index) const;
  void set_capture_size_two(int index, bool value);
  void add_capture_size_two(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      capture_size_two() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_capture_size_two();

  // repeated bool capture_size_three = 23;
  int capture_size_three_size() const;
  void clear_capture_size_three();
  static const int kCaptureSizeThreeFieldNumber = 23;
  bool capture_size_three(int index) const;
  void set_capture_size_three(int index, bool value);
  void add_capture_size_three(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      capture_size_three() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_capture_size_three();

  // repeated bool capture_size_four = 24;
  int capture_size_four_size() const;
  void clear_capture_size_four();
  static const int kCaptureSizeFourFieldNumber = 24;
  bool capture_size_four(int index) const;
  void set_capture_size_four(int index, bool value);
  void add_capture_size_four(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      capture_size_four() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_capture_size_four();

  // repeated bool capture_size_five = 25;
  int capture_size_five_size() const;
  void clear_capture_size_five();
  static const int kCaptureSizeFiveFieldNumber = 25;
  bool capture_size_five(int index) const;
  void set_capture_size_five(int index, bool value);
  void add_capture_size_five(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      capture_size_five() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_capture_size_five();

  // repeated bool capture_size_six = 26;
  int capture_size_six_size() const;
  void clear_capture_size_six();
  static const int kCaptureSizeSixFieldNumber = 26;
  bool capture_size_six(int index) const;
  void set_capture_size_six(int index, bool value);
  void add_capture_size_six(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      capture_size_six() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_capture_size_six();

  // repeated bool capture_size_seven = 27;
  int capture_size_seven_size() const;
  void clear_capture_size_seven();
  static const int kCaptureSizeSevenFieldNumber = 27;
  bool capture_size_seven(int index) const;
  void set_capture_size_seven(int index, bool value);
  void add_capture_size_seven(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      capture_size_seven() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_capture_size_seven();

  // repeated bool capture_size_more = 28;
  int capture_size_more_size() const;
  void clear_capture_size_more();
  static const int kCaptureSizeMoreFieldNumber = 28;
  bool capture_size_more(int index) const;
  void set_capture_size_more(int index, bool value);
  void add_capture_size_more(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      capture_size_more() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_capture_size_more();

  // repeated bool sensibleness = 29;
  int sensibleness_size() const;
  void clear_sensibleness();
  static const int kSensiblenessFieldNumber = 29;
  bool sensibleness(int index) const;
  void set_sensibleness(int index, bool value);
  void add_sensibleness(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      sensibleness() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_sensibleness();

  // repeated bool ko = 30;
  int ko_size() const;
  void clear_ko();
  static const int kKoFieldNumber = 30;
  bool ko(int index) const;
  void set_ko(int index, bool value);
  void add_ko(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      ko() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_ko();

  // repeated bool border = 31;
  int border_size() const;
  void clear_border();
  static const int kBorderFieldNumber = 31;
  bool border(int index) const;
  void set_border(int index, bool value);
  void add_border(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      border() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_border();

  // repeated float position = 32;
  int position_size() const;
  void clear_position();
  static const int kPositionFieldNumber = 32;
  float position(int index) const;
  void set_position(int index, float value);
  void add_position(float value);
  const ::google::protobuf::RepeatedField< float >&
      position() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_position();

  // @@protoc_insertion_point(class_scope:gocnn.RequestV2)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedField< bool > stone_color_our_;
  mutable int _stone_color_our_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > stone_color_oppo_;
  mutable int _stone_color_oppo_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > stone_color_empty_;
  mutable int _stone_color_empty_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > turns_since_one_;
  mutable int _turns_since_one_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > turns_since_two_;
  mutable int _turns_since_two_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > turns_since_three_;
  mutable int _turns_since_three_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > turns_since_four_;
  mutable int _turns_since_four_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > turns_since_five_;
  mutable int _turns_since_five_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > turns_since_six_;
  mutable int _turns_since_six_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > turns_since_seven_;
  mutable int _turns_since_seven_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > turns_since_more_;
  mutable int _turns_since_more_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > liberties_our_one_;
  mutable int _liberties_our_one_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > liberties_our_two_;
  mutable int _liberties_our_two_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > liberties_our_three_;
  mutable int _liberties_our_three_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > liberties_our_more_;
  mutable int _liberties_our_more_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > liberties_oppo_one_;
  mutable int _liberties_oppo_one_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > liberties_oppo_two_;
  mutable int _liberties_oppo_two_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > liberties_oppo_three_;
  mutable int _liberties_oppo_three_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > liberties_oppo_more_;
  mutable int _liberties_oppo_more_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > capture_size_one_;
  mutable int _capture_size_one_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > capture_size_two_;
  mutable int _capture_size_two_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > capture_size_three_;
  mutable int _capture_size_three_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > capture_size_four_;
  mutable int _capture_size_four_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > capture_size_five_;
  mutable int _capture_size_five_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > capture_size_six_;
  mutable int _capture_size_six_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > capture_size_seven_;
  mutable int _capture_size_seven_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > capture_size_more_;
  mutable int _capture_size_more_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > sensibleness_;
  mutable int _sensibleness_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > ko_;
  mutable int _ko_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > border_;
  mutable int _border_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > position_;
  mutable int _position_cached_byte_size_;
  ::google::protobuf::int32 board_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static RequestV2* default_instance_;
};
// -------------------------------------------------------------------

class ResponseV2 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gocnn.ResponseV2) */ {
 public:
  ResponseV2();
  virtual ~ResponseV2();

  ResponseV2(const ResponseV2& from);

  inline ResponseV2& operator=(const ResponseV2& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseV2& default_instance();

  void Swap(ResponseV2* other);

  // implements Message ----------------------------------------------

  inline ResponseV2* New() const { return New(NULL); }

  ResponseV2* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseV2& from);
  void MergeFrom(const ResponseV2& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ResponseV2* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 board_size = 1;
  void clear_board_size();
  static const int kBoardSizeFieldNumber = 1;
  ::google::protobuf::int32 board_size() const;
  void set_board_size(::google::protobuf::int32 value);

  // repeated float possibility = 2;
  int possibility_size() const;
  void clear_possibility();
  static const int kPossibilityFieldNumber = 2;
  float possibility(int index) const;
  void set_possibility(int index, float value);
  void add_possibility(float value);
  const ::google::protobuf::RepeatedField< float >&
      possibility() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_possibility();

  // @@protoc_insertion_point(class_scope:gocnn.ResponseV2)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedField< float > possibility_;
  mutable int _possibility_cached_byte_size_;
  ::google::protobuf::int32 board_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static ResponseV2* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RequestV1

// optional int32 board_size = 1;
inline void RequestV1::clear_board_size() {
  board_size_ = 0;
}
inline ::google::protobuf::int32 RequestV1::board_size() const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.board_size)
  return board_size_;
}
inline void RequestV1::set_board_size(::google::protobuf::int32 value) {
  
  board_size_ = value;
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.board_size)
}

// repeated bool our_group_lib1 = 2;
inline int RequestV1::our_group_lib1_size() const {
  return our_group_lib1_.size();
}
inline void RequestV1::clear_our_group_lib1() {
  our_group_lib1_.Clear();
}
inline bool RequestV1::our_group_lib1(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.our_group_lib1)
  return our_group_lib1_.Get(index);
}
inline void RequestV1::set_our_group_lib1(int index, bool value) {
  our_group_lib1_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.our_group_lib1)
}
inline void RequestV1::add_our_group_lib1(bool value) {
  our_group_lib1_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.our_group_lib1)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::our_group_lib1() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.our_group_lib1)
  return our_group_lib1_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_our_group_lib1() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.our_group_lib1)
  return &our_group_lib1_;
}

// repeated bool our_group_lib2 = 3;
inline int RequestV1::our_group_lib2_size() const {
  return our_group_lib2_.size();
}
inline void RequestV1::clear_our_group_lib2() {
  our_group_lib2_.Clear();
}
inline bool RequestV1::our_group_lib2(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.our_group_lib2)
  return our_group_lib2_.Get(index);
}
inline void RequestV1::set_our_group_lib2(int index, bool value) {
  our_group_lib2_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.our_group_lib2)
}
inline void RequestV1::add_our_group_lib2(bool value) {
  our_group_lib2_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.our_group_lib2)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::our_group_lib2() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.our_group_lib2)
  return our_group_lib2_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_our_group_lib2() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.our_group_lib2)
  return &our_group_lib2_;
}

// repeated bool our_group_lib3_plus = 4;
inline int RequestV1::our_group_lib3_plus_size() const {
  return our_group_lib3_plus_.size();
}
inline void RequestV1::clear_our_group_lib3_plus() {
  our_group_lib3_plus_.Clear();
}
inline bool RequestV1::our_group_lib3_plus(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.our_group_lib3_plus)
  return our_group_lib3_plus_.Get(index);
}
inline void RequestV1::set_our_group_lib3_plus(int index, bool value) {
  our_group_lib3_plus_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.our_group_lib3_plus)
}
inline void RequestV1::add_our_group_lib3_plus(bool value) {
  our_group_lib3_plus_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.our_group_lib3_plus)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::our_group_lib3_plus() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.our_group_lib3_plus)
  return our_group_lib3_plus_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_our_group_lib3_plus() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.our_group_lib3_plus)
  return &our_group_lib3_plus_;
}

// repeated bool oppo_group_lib1 = 5;
inline int RequestV1::oppo_group_lib1_size() const {
  return oppo_group_lib1_.size();
}
inline void RequestV1::clear_oppo_group_lib1() {
  oppo_group_lib1_.Clear();
}
inline bool RequestV1::oppo_group_lib1(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.oppo_group_lib1)
  return oppo_group_lib1_.Get(index);
}
inline void RequestV1::set_oppo_group_lib1(int index, bool value) {
  oppo_group_lib1_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.oppo_group_lib1)
}
inline void RequestV1::add_oppo_group_lib1(bool value) {
  oppo_group_lib1_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.oppo_group_lib1)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::oppo_group_lib1() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.oppo_group_lib1)
  return oppo_group_lib1_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_oppo_group_lib1() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.oppo_group_lib1)
  return &oppo_group_lib1_;
}

// repeated bool oppo_group_lib2 = 6;
inline int RequestV1::oppo_group_lib2_size() const {
  return oppo_group_lib2_.size();
}
inline void RequestV1::clear_oppo_group_lib2() {
  oppo_group_lib2_.Clear();
}
inline bool RequestV1::oppo_group_lib2(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.oppo_group_lib2)
  return oppo_group_lib2_.Get(index);
}
inline void RequestV1::set_oppo_group_lib2(int index, bool value) {
  oppo_group_lib2_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.oppo_group_lib2)
}
inline void RequestV1::add_oppo_group_lib2(bool value) {
  oppo_group_lib2_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.oppo_group_lib2)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::oppo_group_lib2() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.oppo_group_lib2)
  return oppo_group_lib2_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_oppo_group_lib2() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.oppo_group_lib2)
  return &oppo_group_lib2_;
}

// repeated bool oppo_group_lib3_plus = 7;
inline int RequestV1::oppo_group_lib3_plus_size() const {
  return oppo_group_lib3_plus_.size();
}
inline void RequestV1::clear_oppo_group_lib3_plus() {
  oppo_group_lib3_plus_.Clear();
}
inline bool RequestV1::oppo_group_lib3_plus(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.oppo_group_lib3_plus)
  return oppo_group_lib3_plus_.Get(index);
}
inline void RequestV1::set_oppo_group_lib3_plus(int index, bool value) {
  oppo_group_lib3_plus_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.oppo_group_lib3_plus)
}
inline void RequestV1::add_oppo_group_lib3_plus(bool value) {
  oppo_group_lib3_plus_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.oppo_group_lib3_plus)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::oppo_group_lib3_plus() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.oppo_group_lib3_plus)
  return oppo_group_lib3_plus_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_oppo_group_lib3_plus() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.oppo_group_lib3_plus)
  return &oppo_group_lib3_plus_;
}

// repeated bool is_simple_ko = 8;
inline int RequestV1::is_simple_ko_size() const {
  return is_simple_ko_.size();
}
inline void RequestV1::clear_is_simple_ko() {
  is_simple_ko_.Clear();
}
inline bool RequestV1::is_simple_ko(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.is_simple_ko)
  return is_simple_ko_.Get(index);
}
inline void RequestV1::set_is_simple_ko(int index, bool value) {
  is_simple_ko_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.is_simple_ko)
}
inline void RequestV1::add_is_simple_ko(bool value) {
  is_simple_ko_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.is_simple_ko)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::is_simple_ko() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.is_simple_ko)
  return is_simple_ko_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_is_simple_ko() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.is_simple_ko)
  return &is_simple_ko_;
}

// -------------------------------------------------------------------

// ResponseV1

// optional int32 board_size = 1;
inline void ResponseV1::clear_board_size() {
  board_size_ = 0;
}
inline ::google::protobuf::int32 ResponseV1::board_size() const {
  // @@protoc_insertion_point(field_get:gocnn.ResponseV1.board_size)
  return board_size_;
}
inline void ResponseV1::set_board_size(::google::protobuf::int32 value) {
  
  board_size_ = value;
  // @@protoc_insertion_point(field_set:gocnn.ResponseV1.board_size)
}

// repeated float possibility = 2;
inline int ResponseV1::possibility_size() const {
  return possibility_.size();
}
inline void ResponseV1::clear_possibility() {
  possibility_.Clear();
}
inline float ResponseV1::possibility(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.ResponseV1.possibility)
  return possibility_.Get(index);
}
inline void ResponseV1::set_possibility(int index, float value) {
  possibility_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.ResponseV1.possibility)
}
inline void ResponseV1::add_possibility(float value) {
  possibility_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.ResponseV1.possibility)
}
inline const ::google::protobuf::RepeatedField< float >&
ResponseV1::possibility() const {
  // @@protoc_insertion_point(field_list:gocnn.ResponseV1.possibility)
  return possibility_;
}
inline ::google::protobuf::RepeatedField< float >*
ResponseV1::mutable_possibility() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.ResponseV1.possibility)
  return &possibility_;
}

// -------------------------------------------------------------------

// RequestV2

// optional int32 board_size = 1;
inline void RequestV2::clear_board_size() {
  board_size_ = 0;
}
inline ::google::protobuf::int32 RequestV2::board_size() const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.board_size)
  return board_size_;
}
inline void RequestV2::set_board_size(::google::protobuf::int32 value) {
  
  board_size_ = value;
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.board_size)
}

// repeated bool stone_color_our = 2;
inline int RequestV2::stone_color_our_size() const {
  return stone_color_our_.size();
}
inline void RequestV2::clear_stone_color_our() {
  stone_color_our_.Clear();
}
inline bool RequestV2::stone_color_our(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.stone_color_our)
  return stone_color_our_.Get(index);
}
inline void RequestV2::set_stone_color_our(int index, bool value) {
  stone_color_our_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.stone_color_our)
}
inline void RequestV2::add_stone_color_our(bool value) {
  stone_color_our_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.stone_color_our)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::stone_color_our() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.stone_color_our)
  return stone_color_our_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_stone_color_our() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.stone_color_our)
  return &stone_color_our_;
}

// repeated bool stone_color_oppo = 3;
inline int RequestV2::stone_color_oppo_size() const {
  return stone_color_oppo_.size();
}
inline void RequestV2::clear_stone_color_oppo() {
  stone_color_oppo_.Clear();
}
inline bool RequestV2::stone_color_oppo(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.stone_color_oppo)
  return stone_color_oppo_.Get(index);
}
inline void RequestV2::set_stone_color_oppo(int index, bool value) {
  stone_color_oppo_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.stone_color_oppo)
}
inline void RequestV2::add_stone_color_oppo(bool value) {
  stone_color_oppo_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.stone_color_oppo)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::stone_color_oppo() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.stone_color_oppo)
  return stone_color_oppo_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_stone_color_oppo() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.stone_color_oppo)
  return &stone_color_oppo_;
}

// repeated bool stone_color_empty = 4;
inline int RequestV2::stone_color_empty_size() const {
  return stone_color_empty_.size();
}
inline void RequestV2::clear_stone_color_empty() {
  stone_color_empty_.Clear();
}
inline bool RequestV2::stone_color_empty(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.stone_color_empty)
  return stone_color_empty_.Get(index);
}
inline void RequestV2::set_stone_color_empty(int index, bool value) {
  stone_color_empty_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.stone_color_empty)
}
inline void RequestV2::add_stone_color_empty(bool value) {
  stone_color_empty_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.stone_color_empty)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::stone_color_empty() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.stone_color_empty)
  return stone_color_empty_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_stone_color_empty() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.stone_color_empty)
  return &stone_color_empty_;
}

// repeated bool turns_since_one = 5;
inline int RequestV2::turns_since_one_size() const {
  return turns_since_one_.size();
}
inline void RequestV2::clear_turns_since_one() {
  turns_since_one_.Clear();
}
inline bool RequestV2::turns_since_one(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.turns_since_one)
  return turns_since_one_.Get(index);
}
inline void RequestV2::set_turns_since_one(int index, bool value) {
  turns_since_one_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.turns_since_one)
}
inline void RequestV2::add_turns_since_one(bool value) {
  turns_since_one_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.turns_since_one)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::turns_since_one() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.turns_since_one)
  return turns_since_one_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_turns_since_one() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.turns_since_one)
  return &turns_since_one_;
}

// repeated bool turns_since_two = 6;
inline int RequestV2::turns_since_two_size() const {
  return turns_since_two_.size();
}
inline void RequestV2::clear_turns_since_two() {
  turns_since_two_.Clear();
}
inline bool RequestV2::turns_since_two(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.turns_since_two)
  return turns_since_two_.Get(index);
}
inline void RequestV2::set_turns_since_two(int index, bool value) {
  turns_since_two_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.turns_since_two)
}
inline void RequestV2::add_turns_since_two(bool value) {
  turns_since_two_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.turns_since_two)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::turns_since_two() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.turns_since_two)
  return turns_since_two_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_turns_since_two() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.turns_since_two)
  return &turns_since_two_;
}

// repeated bool turns_since_three = 7;
inline int RequestV2::turns_since_three_size() const {
  return turns_since_three_.size();
}
inline void RequestV2::clear_turns_since_three() {
  turns_since_three_.Clear();
}
inline bool RequestV2::turns_since_three(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.turns_since_three)
  return turns_since_three_.Get(index);
}
inline void RequestV2::set_turns_since_three(int index, bool value) {
  turns_since_three_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.turns_since_three)
}
inline void RequestV2::add_turns_since_three(bool value) {
  turns_since_three_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.turns_since_three)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::turns_since_three() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.turns_since_three)
  return turns_since_three_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_turns_since_three() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.turns_since_three)
  return &turns_since_three_;
}

// repeated bool turns_since_four = 8;
inline int RequestV2::turns_since_four_size() const {
  return turns_since_four_.size();
}
inline void RequestV2::clear_turns_since_four() {
  turns_since_four_.Clear();
}
inline bool RequestV2::turns_since_four(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.turns_since_four)
  return turns_since_four_.Get(index);
}
inline void RequestV2::set_turns_since_four(int index, bool value) {
  turns_since_four_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.turns_since_four)
}
inline void RequestV2::add_turns_since_four(bool value) {
  turns_since_four_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.turns_since_four)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::turns_since_four() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.turns_since_four)
  return turns_since_four_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_turns_since_four() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.turns_since_four)
  return &turns_since_four_;
}

// repeated bool turns_since_five = 9;
inline int RequestV2::turns_since_five_size() const {
  return turns_since_five_.size();
}
inline void RequestV2::clear_turns_since_five() {
  turns_since_five_.Clear();
}
inline bool RequestV2::turns_since_five(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.turns_since_five)
  return turns_since_five_.Get(index);
}
inline void RequestV2::set_turns_since_five(int index, bool value) {
  turns_since_five_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.turns_since_five)
}
inline void RequestV2::add_turns_since_five(bool value) {
  turns_since_five_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.turns_since_five)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::turns_since_five() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.turns_since_five)
  return turns_since_five_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_turns_since_five() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.turns_since_five)
  return &turns_since_five_;
}

// repeated bool turns_since_six = 10;
inline int RequestV2::turns_since_six_size() const {
  return turns_since_six_.size();
}
inline void RequestV2::clear_turns_since_six() {
  turns_since_six_.Clear();
}
inline bool RequestV2::turns_since_six(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.turns_since_six)
  return turns_since_six_.Get(index);
}
inline void RequestV2::set_turns_since_six(int index, bool value) {
  turns_since_six_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.turns_since_six)
}
inline void RequestV2::add_turns_since_six(bool value) {
  turns_since_six_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.turns_since_six)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::turns_since_six() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.turns_since_six)
  return turns_since_six_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_turns_since_six() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.turns_since_six)
  return &turns_since_six_;
}

// repeated bool turns_since_seven = 11;
inline int RequestV2::turns_since_seven_size() const {
  return turns_since_seven_.size();
}
inline void RequestV2::clear_turns_since_seven() {
  turns_since_seven_.Clear();
}
inline bool RequestV2::turns_since_seven(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.turns_since_seven)
  return turns_since_seven_.Get(index);
}
inline void RequestV2::set_turns_since_seven(int index, bool value) {
  turns_since_seven_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.turns_since_seven)
}
inline void RequestV2::add_turns_since_seven(bool value) {
  turns_since_seven_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.turns_since_seven)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::turns_since_seven() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.turns_since_seven)
  return turns_since_seven_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_turns_since_seven() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.turns_since_seven)
  return &turns_since_seven_;
}

// repeated bool turns_since_more = 12;
inline int RequestV2::turns_since_more_size() const {
  return turns_since_more_.size();
}
inline void RequestV2::clear_turns_since_more() {
  turns_since_more_.Clear();
}
inline bool RequestV2::turns_since_more(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.turns_since_more)
  return turns_since_more_.Get(index);
}
inline void RequestV2::set_turns_since_more(int index, bool value) {
  turns_since_more_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.turns_since_more)
}
inline void RequestV2::add_turns_since_more(bool value) {
  turns_since_more_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.turns_since_more)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::turns_since_more() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.turns_since_more)
  return turns_since_more_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_turns_since_more() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.turns_since_more)
  return &turns_since_more_;
}

// repeated bool liberties_our_one = 13;
inline int RequestV2::liberties_our_one_size() const {
  return liberties_our_one_.size();
}
inline void RequestV2::clear_liberties_our_one() {
  liberties_our_one_.Clear();
}
inline bool RequestV2::liberties_our_one(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.liberties_our_one)
  return liberties_our_one_.Get(index);
}
inline void RequestV2::set_liberties_our_one(int index, bool value) {
  liberties_our_one_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.liberties_our_one)
}
inline void RequestV2::add_liberties_our_one(bool value) {
  liberties_our_one_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.liberties_our_one)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::liberties_our_one() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.liberties_our_one)
  return liberties_our_one_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_liberties_our_one() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.liberties_our_one)
  return &liberties_our_one_;
}

// repeated bool liberties_our_two = 14;
inline int RequestV2::liberties_our_two_size() const {
  return liberties_our_two_.size();
}
inline void RequestV2::clear_liberties_our_two() {
  liberties_our_two_.Clear();
}
inline bool RequestV2::liberties_our_two(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.liberties_our_two)
  return liberties_our_two_.Get(index);
}
inline void RequestV2::set_liberties_our_two(int index, bool value) {
  liberties_our_two_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.liberties_our_two)
}
inline void RequestV2::add_liberties_our_two(bool value) {
  liberties_our_two_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.liberties_our_two)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::liberties_our_two() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.liberties_our_two)
  return liberties_our_two_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_liberties_our_two() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.liberties_our_two)
  return &liberties_our_two_;
}

// repeated bool liberties_our_three = 15;
inline int RequestV2::liberties_our_three_size() const {
  return liberties_our_three_.size();
}
inline void RequestV2::clear_liberties_our_three() {
  liberties_our_three_.Clear();
}
inline bool RequestV2::liberties_our_three(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.liberties_our_three)
  return liberties_our_three_.Get(index);
}
inline void RequestV2::set_liberties_our_three(int index, bool value) {
  liberties_our_three_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.liberties_our_three)
}
inline void RequestV2::add_liberties_our_three(bool value) {
  liberties_our_three_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.liberties_our_three)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::liberties_our_three() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.liberties_our_three)
  return liberties_our_three_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_liberties_our_three() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.liberties_our_three)
  return &liberties_our_three_;
}

// repeated bool liberties_our_more = 16;
inline int RequestV2::liberties_our_more_size() const {
  return liberties_our_more_.size();
}
inline void RequestV2::clear_liberties_our_more() {
  liberties_our_more_.Clear();
}
inline bool RequestV2::liberties_our_more(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.liberties_our_more)
  return liberties_our_more_.Get(index);
}
inline void RequestV2::set_liberties_our_more(int index, bool value) {
  liberties_our_more_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.liberties_our_more)
}
inline void RequestV2::add_liberties_our_more(bool value) {
  liberties_our_more_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.liberties_our_more)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::liberties_our_more() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.liberties_our_more)
  return liberties_our_more_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_liberties_our_more() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.liberties_our_more)
  return &liberties_our_more_;
}

// repeated bool liberties_oppo_one = 17;
inline int RequestV2::liberties_oppo_one_size() const {
  return liberties_oppo_one_.size();
}
inline void RequestV2::clear_liberties_oppo_one() {
  liberties_oppo_one_.Clear();
}
inline bool RequestV2::liberties_oppo_one(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.liberties_oppo_one)
  return liberties_oppo_one_.Get(index);
}
inline void RequestV2::set_liberties_oppo_one(int index, bool value) {
  liberties_oppo_one_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.liberties_oppo_one)
}
inline void RequestV2::add_liberties_oppo_one(bool value) {
  liberties_oppo_one_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.liberties_oppo_one)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::liberties_oppo_one() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.liberties_oppo_one)
  return liberties_oppo_one_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_liberties_oppo_one() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.liberties_oppo_one)
  return &liberties_oppo_one_;
}

// repeated bool liberties_oppo_two = 18;
inline int RequestV2::liberties_oppo_two_size() const {
  return liberties_oppo_two_.size();
}
inline void RequestV2::clear_liberties_oppo_two() {
  liberties_oppo_two_.Clear();
}
inline bool RequestV2::liberties_oppo_two(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.liberties_oppo_two)
  return liberties_oppo_two_.Get(index);
}
inline void RequestV2::set_liberties_oppo_two(int index, bool value) {
  liberties_oppo_two_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.liberties_oppo_two)
}
inline void RequestV2::add_liberties_oppo_two(bool value) {
  liberties_oppo_two_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.liberties_oppo_two)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::liberties_oppo_two() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.liberties_oppo_two)
  return liberties_oppo_two_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_liberties_oppo_two() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.liberties_oppo_two)
  return &liberties_oppo_two_;
}

// repeated bool liberties_oppo_three = 19;
inline int RequestV2::liberties_oppo_three_size() const {
  return liberties_oppo_three_.size();
}
inline void RequestV2::clear_liberties_oppo_three() {
  liberties_oppo_three_.Clear();
}
inline bool RequestV2::liberties_oppo_three(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.liberties_oppo_three)
  return liberties_oppo_three_.Get(index);
}
inline void RequestV2::set_liberties_oppo_three(int index, bool value) {
  liberties_oppo_three_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.liberties_oppo_three)
}
inline void RequestV2::add_liberties_oppo_three(bool value) {
  liberties_oppo_three_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.liberties_oppo_three)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::liberties_oppo_three() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.liberties_oppo_three)
  return liberties_oppo_three_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_liberties_oppo_three() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.liberties_oppo_three)
  return &liberties_oppo_three_;
}

// repeated bool liberties_oppo_more = 20;
inline int RequestV2::liberties_oppo_more_size() const {
  return liberties_oppo_more_.size();
}
inline void RequestV2::clear_liberties_oppo_more() {
  liberties_oppo_more_.Clear();
}
inline bool RequestV2::liberties_oppo_more(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.liberties_oppo_more)
  return liberties_oppo_more_.Get(index);
}
inline void RequestV2::set_liberties_oppo_more(int index, bool value) {
  liberties_oppo_more_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.liberties_oppo_more)
}
inline void RequestV2::add_liberties_oppo_more(bool value) {
  liberties_oppo_more_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.liberties_oppo_more)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::liberties_oppo_more() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.liberties_oppo_more)
  return liberties_oppo_more_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_liberties_oppo_more() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.liberties_oppo_more)
  return &liberties_oppo_more_;
}

// repeated bool capture_size_one = 21;
inline int RequestV2::capture_size_one_size() const {
  return capture_size_one_.size();
}
inline void RequestV2::clear_capture_size_one() {
  capture_size_one_.Clear();
}
inline bool RequestV2::capture_size_one(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.capture_size_one)
  return capture_size_one_.Get(index);
}
inline void RequestV2::set_capture_size_one(int index, bool value) {
  capture_size_one_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.capture_size_one)
}
inline void RequestV2::add_capture_size_one(bool value) {
  capture_size_one_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.capture_size_one)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::capture_size_one() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.capture_size_one)
  return capture_size_one_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_capture_size_one() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.capture_size_one)
  return &capture_size_one_;
}

// repeated bool capture_size_two = 22;
inline int RequestV2::capture_size_two_size() const {
  return capture_size_two_.size();
}
inline void RequestV2::clear_capture_size_two() {
  capture_size_two_.Clear();
}
inline bool RequestV2::capture_size_two(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.capture_size_two)
  return capture_size_two_.Get(index);
}
inline void RequestV2::set_capture_size_two(int index, bool value) {
  capture_size_two_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.capture_size_two)
}
inline void RequestV2::add_capture_size_two(bool value) {
  capture_size_two_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.capture_size_two)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::capture_size_two() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.capture_size_two)
  return capture_size_two_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_capture_size_two() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.capture_size_two)
  return &capture_size_two_;
}

// repeated bool capture_size_three = 23;
inline int RequestV2::capture_size_three_size() const {
  return capture_size_three_.size();
}
inline void RequestV2::clear_capture_size_three() {
  capture_size_three_.Clear();
}
inline bool RequestV2::capture_size_three(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.capture_size_three)
  return capture_size_three_.Get(index);
}
inline void RequestV2::set_capture_size_three(int index, bool value) {
  capture_size_three_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.capture_size_three)
}
inline void RequestV2::add_capture_size_three(bool value) {
  capture_size_three_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.capture_size_three)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::capture_size_three() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.capture_size_three)
  return capture_size_three_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_capture_size_three() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.capture_size_three)
  return &capture_size_three_;
}

// repeated bool capture_size_four = 24;
inline int RequestV2::capture_size_four_size() const {
  return capture_size_four_.size();
}
inline void RequestV2::clear_capture_size_four() {
  capture_size_four_.Clear();
}
inline bool RequestV2::capture_size_four(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.capture_size_four)
  return capture_size_four_.Get(index);
}
inline void RequestV2::set_capture_size_four(int index, bool value) {
  capture_size_four_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.capture_size_four)
}
inline void RequestV2::add_capture_size_four(bool value) {
  capture_size_four_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.capture_size_four)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::capture_size_four() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.capture_size_four)
  return capture_size_four_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_capture_size_four() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.capture_size_four)
  return &capture_size_four_;
}

// repeated bool capture_size_five = 25;
inline int RequestV2::capture_size_five_size() const {
  return capture_size_five_.size();
}
inline void RequestV2::clear_capture_size_five() {
  capture_size_five_.Clear();
}
inline bool RequestV2::capture_size_five(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.capture_size_five)
  return capture_size_five_.Get(index);
}
inline void RequestV2::set_capture_size_five(int index, bool value) {
  capture_size_five_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.capture_size_five)
}
inline void RequestV2::add_capture_size_five(bool value) {
  capture_size_five_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.capture_size_five)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::capture_size_five() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.capture_size_five)
  return capture_size_five_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_capture_size_five() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.capture_size_five)
  return &capture_size_five_;
}

// repeated bool capture_size_six = 26;
inline int RequestV2::capture_size_six_size() const {
  return capture_size_six_.size();
}
inline void RequestV2::clear_capture_size_six() {
  capture_size_six_.Clear();
}
inline bool RequestV2::capture_size_six(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.capture_size_six)
  return capture_size_six_.Get(index);
}
inline void RequestV2::set_capture_size_six(int index, bool value) {
  capture_size_six_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.capture_size_six)
}
inline void RequestV2::add_capture_size_six(bool value) {
  capture_size_six_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.capture_size_six)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::capture_size_six() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.capture_size_six)
  return capture_size_six_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_capture_size_six() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.capture_size_six)
  return &capture_size_six_;
}

// repeated bool capture_size_seven = 27;
inline int RequestV2::capture_size_seven_size() const {
  return capture_size_seven_.size();
}
inline void RequestV2::clear_capture_size_seven() {
  capture_size_seven_.Clear();
}
inline bool RequestV2::capture_size_seven(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.capture_size_seven)
  return capture_size_seven_.Get(index);
}
inline void RequestV2::set_capture_size_seven(int index, bool value) {
  capture_size_seven_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.capture_size_seven)
}
inline void RequestV2::add_capture_size_seven(bool value) {
  capture_size_seven_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.capture_size_seven)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::capture_size_seven() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.capture_size_seven)
  return capture_size_seven_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_capture_size_seven() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.capture_size_seven)
  return &capture_size_seven_;
}

// repeated bool capture_size_more = 28;
inline int RequestV2::capture_size_more_size() const {
  return capture_size_more_.size();
}
inline void RequestV2::clear_capture_size_more() {
  capture_size_more_.Clear();
}
inline bool RequestV2::capture_size_more(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.capture_size_more)
  return capture_size_more_.Get(index);
}
inline void RequestV2::set_capture_size_more(int index, bool value) {
  capture_size_more_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.capture_size_more)
}
inline void RequestV2::add_capture_size_more(bool value) {
  capture_size_more_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.capture_size_more)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::capture_size_more() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.capture_size_more)
  return capture_size_more_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_capture_size_more() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.capture_size_more)
  return &capture_size_more_;
}

// repeated bool sensibleness = 29;
inline int RequestV2::sensibleness_size() const {
  return sensibleness_.size();
}
inline void RequestV2::clear_sensibleness() {
  sensibleness_.Clear();
}
inline bool RequestV2::sensibleness(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.sensibleness)
  return sensibleness_.Get(index);
}
inline void RequestV2::set_sensibleness(int index, bool value) {
  sensibleness_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.sensibleness)
}
inline void RequestV2::add_sensibleness(bool value) {
  sensibleness_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.sensibleness)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::sensibleness() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.sensibleness)
  return sensibleness_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_sensibleness() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.sensibleness)
  return &sensibleness_;
}

// repeated bool ko = 30;
inline int RequestV2::ko_size() const {
  return ko_.size();
}
inline void RequestV2::clear_ko() {
  ko_.Clear();
}
inline bool RequestV2::ko(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.ko)
  return ko_.Get(index);
}
inline void RequestV2::set_ko(int index, bool value) {
  ko_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.ko)
}
inline void RequestV2::add_ko(bool value) {
  ko_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.ko)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::ko() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.ko)
  return ko_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_ko() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.ko)
  return &ko_;
}

// repeated bool border = 31;
inline int RequestV2::border_size() const {
  return border_.size();
}
inline void RequestV2::clear_border() {
  border_.Clear();
}
inline bool RequestV2::border(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.border)
  return border_.Get(index);
}
inline void RequestV2::set_border(int index, bool value) {
  border_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.border)
}
inline void RequestV2::add_border(bool value) {
  border_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.border)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::border() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.border)
  return border_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_border() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.border)
  return &border_;
}

// repeated float position = 32;
inline int RequestV2::position_size() const {
  return position_.size();
}
inline void RequestV2::clear_position() {
  position_.Clear();
}
inline float RequestV2::position(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.position)
  return position_.Get(index);
}
inline void RequestV2::set_position(int index, float value) {
  position_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.position)
}
inline void RequestV2::add_position(float value) {
  position_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.position)
}
inline const ::google::protobuf::RepeatedField< float >&
RequestV2::position() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.position)
  return position_;
}
inline ::google::protobuf::RepeatedField< float >*
RequestV2::mutable_position() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.position)
  return &position_;
}

// -------------------------------------------------------------------

// ResponseV2

// optional int32 board_size = 1;
inline void ResponseV2::clear_board_size() {
  board_size_ = 0;
}
inline ::google::protobuf::int32 ResponseV2::board_size() const {
  // @@protoc_insertion_point(field_get:gocnn.ResponseV2.board_size)
  return board_size_;
}
inline void ResponseV2::set_board_size(::google::protobuf::int32 value) {
  
  board_size_ = value;
  // @@protoc_insertion_point(field_set:gocnn.ResponseV2.board_size)
}

// repeated float possibility = 2;
inline int ResponseV2::possibility_size() const {
  return possibility_.size();
}
inline void ResponseV2::clear_possibility() {
  possibility_.Clear();
}
inline float ResponseV2::possibility(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.ResponseV2.possibility)
  return possibility_.Get(index);
}
inline void ResponseV2::set_possibility(int index, float value) {
  possibility_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.ResponseV2.possibility)
}
inline void ResponseV2::add_possibility(float value) {
  possibility_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.ResponseV2.possibility)
}
inline const ::google::protobuf::RepeatedField< float >&
ResponseV2::possibility() const {
  // @@protoc_insertion_point(field_list:gocnn.ResponseV2.possibility)
  return possibility_;
}
inline ::google::protobuf::RepeatedField< float >*
ResponseV2::mutable_possibility() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.ResponseV2.possibility)
  return &possibility_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace gocnn

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
